springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    com.travelplan: INFO
    dev.langchain4j: INFO

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
