eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:discovery-server}
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 15000

logging:
  level:
    root: WARN
    com.travelplan: INFO

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
