server:
  port: 8091

spring:
  application:
    name: ecommerce-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: "D:/travel-plan-platform/ecommerce-uploads/"

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET:your-secret-key}