spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.travelplan.event: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: INFO
